[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'junegunn/vim-emoji'

[[plugins]]
repo = 'rhysd/vim-operator-surround'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo = 'junegunn/vim-emoji'

[[plugins]]
repo = 'rhysd/github-complete.vim'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'jnwhiteh/vim-golang'
on_ft = 'go'

[[plugins]]
repo = 'vim-jp/vim-go-extra'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'thinca/vim-visualstar'

[[plugins]]
repo = 'sickill/vim-pasta'

[[plugins]]
call dein#add('Yggdroot/indentLine')



