[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'rhysd/accelerated-jk'

[[plugins]]
repo = 'edkolev/tmuxline.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'mhinz/vim-startify'

[[plugins]]
repo = 'b4b4r07/vim-hcl'

[[plugins]]
repo = 'lifepillar/vim-solarized8'

[[plugins]]
repo = 'vim-jp/vim-go-extra'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'lifepillar/vim-solarized8'

[[plugins]] # React JSX syntax pretty highlighting for vim
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript', 'typescript']

[[plugins]] # TypesSript syntax files for Vim
repo  = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo  = 'pangloss/vim-javascript'
on_ft = ['javascript']
